### ISSUE TITLE
新しい投稿があると最下部にスクロールしてしまう

### ISSUE THREAD

**Issue by mass10** [ihiroky/live-comment#112]
### 概要
* 過去の投稿を見ているとき、新しい投稿が発生すると最下部にスクロールします。

### 期待する動き
* スクロールしないでほしい。

**Comment by ihiroky** [comment]
これは仕様としてこうしています。
この挙動をON/OFFできるようにすることを検討します。

**Comment by ihiroky** [comment]
https://github.com/ihiroky/live-comment/pull/118
