### ISSUE TITLE
[Windows] 透明ウィンドウのサイズがおかしい？

### ISSUE THREAD

**Issue by mass10** [ihiroky/live-comment#113]
## 概要
* 透明ウィンドウのサイズがちょっと大きいようです。

![image](https://user-images.githubusercontent.com/2055840/127587824-ca8bc5db-6bb9-464a-b1e6-a0b4f0497021.png)

## 補足
* 立ち上げただけでは異常なし
* コメントが投稿された瞬間に、タテヨコスクロールバーが出現する
* コメントが消えると、タテスクロールバーが消える。ヨコスクロールバーは残る。
* タスクバーは「自動的に隠す」にしています。

**Comment by ihiroky** [comment]
https://github.com/ihiroky/live-comment/pull/114

**Comment by ihiroky** [comment]
https://github.com/ihiroky/live-comment/releases/tag/v0.2.5
https://github.com/ihiroky/live-comment/tree/v0.2.5
